services:
  php:
    image: php:8.2-fpm
    container_name: php_container
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: Afpa1234
      MYSQL_DATABASE: sf_district
      MYSQL_USER: admin
      MYSQL_PASSWORD: Afpa1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  mariadb_data:
