services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/resturant_projet_sf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  
  php:
    image: php:8.2-fpm
    container_name: php_container
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: Afpa1234
      MYSQL_DATABASE: sf_district
      MYSQL_USER: admin
      MYSQL_PASSWORD: Afpa1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"

  symfony:
    image: php:8.2-cli
    container_name: symfony_container
    restart: always
    working_dir: /var/www/resturant_projet_sf
    volumes:
      - .:/var/www/resturant_projet_sf
    depends_on:
      - db
    command: >
      bash -c "composer install && symfony server:start"

volumes:
  mariadb_data:
